name: CI/CD FastAPI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Login Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Definir TAG
      run: echo "tag=$(date +%s)" >> $GITHUB_ENV

    - name: Build imagem
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ env.tag }} .

    - name: Push imagem
      run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ env.tag }}

    - name: Clonar repo de manifests e atualizar imagem
      run: |
        git clone git@github.com:Sabrina-sz/fastApi-manifests.git
        cd fastApi-manifests
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ env.tag }}|" deployment.yaml
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add deployment.yaml
        git commit -m "update image tag ${{ env.tag }}"
        git push

