name: CI/CD FastAPI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurando o SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Premissão para o GitHub à lista de hosts confiáveis
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Login Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Definição de TAG
      run: echo "tag=$(date +%s)" >> $GITHUB_ENV

    - name: Build imagem
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ env.tag }} .

    - name: Push imagem
      run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ env.tag }}

    - name: Clonando repo(2) de manifests e atualizando a imagem
      run: |
        git clone git@github.com:Sabrina-sz/projeto-ci-cd-fastapi-manifests.git
        cd projeto-ci-cd-fastapi-manifests
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ env.tag }}|" k8s/deployment.yaml
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add deployment.yaml
        git commit -m "update image tag ${{ env.tag }}"
        git push


